version: '3'

services:
  app:
    image: puppeteer-alpine:edge
    build: .
    user: "pptruser:pptruser"
    container_name: puppeteer-alpine
    environment:
      NODE_ENV: "development"
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
      PUPPETEER_EXECUTABLE_PATH: "/usr/bin/chromium-browser"
    volumes:
      - ./:/usr/src/app
    working_dir: "/usr/src/app"
